### ISSUE TITLE
下单失败

### ISSUE THREAD

**Issue by hongweipeng** [stvea/StveaNikeBot#2]
下单返回 `{'message': 'Launch is not active', 'code': 'LAUNCH_NOT_ACTIVE'}`

下单似乎已经不是通过api.nike.com/launch/entries/v2这个接口了

**Comment by Vantiboolean** [comment]
您好，想问问其他的问题。您实现这个代码的时候Access Token能通过refresh token来获取到嘛？我这里测试post之后就会提示[{'code': 99001, 'message': 'Unauthorized Request - Failed Basic Authorization.'}]

**Comment by hongweipeng** [comment]
> 能通过refresh token来获取到嘛？

能啊

**Comment by Vantiboolean** [comment]
> > 能通过refresh token来获取到嘛？
> 
> 能啊

您好，能加个您的联系方式嘛？我看这issue里面一共就咱俩。互助

**Comment by HengCC** [comment]
@hongweipeng  如果变了 抓包分析新地址就行了

**Comment by spacey0409** [comment]
> > > 能通过refresh token来获取到嘛？
> > 
> > 
> > 能啊
> 
> 您好，能加个您的联系方式嘛？我看这issue里面一共就咱俩。互助

现在还弄这个了吗

**Comment by HengCC** [comment]
移动端除了分析接口地址.  还得分析另外一个东西. 很长时间不弄我已经不记得叫什么名字了. 对他们来说是一个边缘部署的防机器人的程序. 他会采集一些信息来确定你是不是机器在操作.   所以单纯的知道接口格式来进行调用会直接被这个边缘部署的程序拦截掉.

**Comment by spacey0409** [comment]
@HengCC sensor_data吗

**Comment by HengCC** [comment]
是的. 除此之外还有几个cookie也是很重要的 . 都是被检查的参数.

**Comment by spacey0409** [comment]
@HengCC 我之前研究出来过 但是不稳定 改写了sensor_data的js文件 大部分情况生成的sensor_data发送给服务器返回给我的_abck可以执行特定请求 后面开始抽风经常失败 可能我被风控检测到了 sensor_data的某些参数不能写死

**Comment by HengCC** [comment]
sensor_data 字面量是类似收集"传感器得到的数据" , 因此事实上得到的数据应该是具有一定的变动性和不可预测性.  我上次看过他们的那个检测文档.  他们有一定的机器学习能力. 能够做到一些基于"学习"得到的检测. 因此你请求失败是很正常的.  事实上你要做的整个流程中也就获取sensor和相关的cookie是难点. 其他的通过抓包都很容易.

**Comment by spacey0409** [comment]
@HengCC 可以分享下检测文档吗

**Comment by spacey0409** [comment]
@HengCC 网页版一直进行抽签一直是失败的 貌似snkrs只能在移动端进行 我当时转到移动端被弄的没脾气就放弃了

**Comment by HengCC** [comment]
文档我之前上传到github,被官方举报侵权了. 我已经删除了. 现在我一时也可能找不到相关的文档. 你可以自己根据一些关键字去google搜索应该还能找到,  网页版的我看的大多数都是通过无头浏览器来模拟的.

**Comment by hongweipeng** [comment]
@spacey0409 已经不在搞这个了
