### ISSUE TITLE
Login through api

### ISSUE THREAD

**Issue by sergiodb92** [stvea/StveaNikeBot#4]
Hello stvea, how do you login through the nike api?

I get a 401 unauthorized request error.

Can also contact me on sdb__92@hotmail.com

**Comment by Vantiboolean** [comment]
@sergiodb92 hi,im a developer who is learning this repo. ive sending messages to the author but not respose me until now. 
ive working on it for weeks, what do u mean use api to login on the NIKE website?As far as i am concerned its using SELENIUM to logon by simulated landing.

**Comment by sergiodb92** [comment]
@lhz1208 Can we talk in private? wechat id: sergionike or see my email above

**Comment by HengCC** [comment]
@sergiodb92 you must understand the akamai's working mechanism. then you may resolve the 401 error. but the infomation of this  is very very lack. So I suggest you  go to their official website which may be  find some infomation.

**Comment by sergiodb92** [comment]
@HengCC Thank you
